[package]
name = "hlua"
version = "0.1.7"
authors = [ "pierre.krieger1708@gmail.com" ]
description = "Zero-cost high-level wrapper for Lua"
repository = "https://github.com/tomaka/hlua"
documentation = "http://tomaka.github.io/hlua/hlua/index.html"
license = "MIT"

[dependencies.liblua_sys]
path = "../liblua-sys"
